const List <String> iconImgs = [
  "assets/images/icons8-add-500.png",
  "assets/images/icons8-approval-500.png",
  "assets/images/icons8-classic-music-500.png",
  "assets/images/icons8-clothes-500.png",
  "assets/images/icons8-coffee-500.png",
  "assets/images/icons8-country-music-500.png",
  "assets/images/icons8-dj-500.png",
  "assets/images/icons8-electronic-music-500.png",
  "assets/images/icons8-hamburger-500.png",
  "assets/images/icons8-health-book-500.png",
  "assets/images/icons8-heat-map-500.png",
  "assets/images/icons8-international-music-500.png",
  "assets/images/icons8-journey-500.png",
  "assets/images/icons8-layers-500.png",
  "assets/images/icons8-medical-bag-500.png",
  "assets/images/icons8-metal-music-500.png",
  "assets/images/icons8-outdoor-swimming-pool-500.png",
  "assets/images/icons8-restaurant-500.png",
  "assets/images/icons8-rock-music-500.png",
  "assets/images/icons8-saxophone-500.png",
  "assets/images/icons8-sent-500.png",
  "assets/images/icons8-singing-500.png",
  "assets/images/icons8-sms-500.png",
  "assets/images/icons8-stage-500.png",
  "assets/images/icons8-taco-500.png",
  "assets/images/icons8-thumbs-up-down-500.png",
  "assets/images/icons8-toilet-500.png",
  "assets/images/icons8-treatment-500.png",
  "assets/images/icons8-user-location-500.png",
  "assets/images/icons8-water-500.png"
];

const List <String> stageIconsImgs = [
  'assets/images/stages/Main-stage-500.png',
  'assets/images/stages/Second-stage-500.png',
];