// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSwIeLlDrS6_B2QmSGHI0tLkp_qvTT5UQ',
    appId: '1:1042849521769:web:2c7fbc558b9d352c7f82f8',
    messagingSenderId: '1042849521769',
    projectId: 'herewer-a1d7b',
    authDomain: 'herewer-a1d7b.firebaseapp.com',
    storageBucket: 'herewer-a1d7b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbwsGq5D5JjFDXHmm0A0jwh9mcHQ7GeaE',
    appId: '1:1042849521769:android:72adb326178683e47f82f8',
    messagingSenderId: '1042849521769',
    projectId: 'herewer-a1d7b',
    storageBucket: 'herewer-a1d7b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvINqugy-iR7Qk-sEtgt3PBMxISLNMqSI',
    appId: '1:1042849521769:ios:e03ed34f6d416af37f82f8',
    messagingSenderId: '1042849521769',
    projectId: 'herewer-a1d7b',
    storageBucket: 'herewer-a1d7b.appspot.com',
    iosClientId: '1042849521769-f74hr2m9r6kej6chdekt51hvm5pl20su.apps.googleusercontent.com',
    iosBundleId: 'com.codingfactory.herewer',
  );
}
