/// Flutter icons HereWeRIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HereWeRIcons
///      fonts:
///       - asset: fonts/HereWeRIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HereWeRIcons {
  HereWeRIcons._();

  static const _kFontFam = 'HereWeRIcons';
  static const String? _kFontPkg = null;

  static const IconData icons8_about_64 = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_add_64 = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_approval_64 = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_atm_64 = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_beer_mug_64 = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_camping_tent_64 = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_charging_battery_64 = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_classic_music_64 = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_clear_filters_64 = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_clothes_64 = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_cocktail_64 = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_coffee_64 = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_coffee_to_go_64 = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_cola_64 = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_comments_64 = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_communication_64 = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_compass_64 = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_country_music_64 = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_crowd_64 = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_customer_64 = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_dancing_64 = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_dj_64 = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_electronic_music_64 = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_entering_geo_fence_64 = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_export_64 = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_facebook_64 = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_facebook_like_64 = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_favorite_64 = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_filter_64 = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_grass_64 = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_hamburger_64 = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_hand_peace_64 = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_health_book_64 = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_heat_map_64 = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_instagram_64 = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_international_music_64 = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_journey_64 = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_lake_64 = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_layers_64 = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_location_64 = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_location_update_64 = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_logout_64 = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_lol_64 = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_loudspeaker_64 = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_love_64 = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_map_marker_64 = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_medical_bag_64 = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_metal_music_64 = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_micro_64 = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_microphone_64 = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_my_location_64 = IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_navigation_64 = IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_new_64 = IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_north_direction_64 = IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_notification_64 = IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_outdoor_swimming_pool_64 = IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_path_64 = IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_people_64 = IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_pint_64 = IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_place_marker_64 = IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_present_64 = IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_push_notifications_64 = IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_rating_circled_64 = IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_restaurant_64 = IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_rock_music_64 = IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_saxophone_64 = IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_schedule_64 = IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_search_64 = IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_sent_64 = IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_share_64 = IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_show_password_64 = IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_sign_out_64 = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_singing_64 = IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_sms_64 = IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_snare_drum_64 = IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_soda_64 = IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_stage_64 = IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_taco_64 = IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_theme_park_64 = IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_thumbs_up_down_64 = IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_tiktok_64 = IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_toilet_64 = IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_treatment_64 = IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_twitter_64 = IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_user_groups_64 = IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_user_location_64 = IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_voice_64 = IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icons8_water_64 = IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
